services:
  app:
    build: .

    container_name: ewalletbunker_app

    volumes:
      - .:/app
      - node_modules:/app/node_modules

    environment:
      NODE_ENV: development

    stdin_open: true
    tty: true

    command: npx expo start --tunnel

volumes:
  node_modules: